@port=8084
@host=localhost
@url=http://{{host}}:{{port}}
POST {{url}}/user
Content-Type:application/json

{
    "username":"zhaoliu",
    "account":"dingyi",
    "password":"123",
    "re_password":"admin"
}

###
GET {{url}}/user/6
Authorization:A

###
GET {{url}}/user?page=2&size=10

###
POST  {{url}}/register
Content-Type:application/json

{
    "account":"dingyi",
    "password":"123",
    "re_password":"123"
}