mode: "dev"
port: 8084
log:
  level: "info"
  web_log_name: "web.log"
  log_file_path: "./log/"
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "g5627327"
  dbname: "data_test"
  # 连接超时
  timeout: "10s"
  # 读超时
  readTimeout: "30s"
  # 写超时
  writeTimeout: "60s"
  # 获取本地时区
  loc: "Local"
  # 使用UTF8字符集
  charset: "utf8mb4"
  # 启用时间戳类型
  parseTime: true
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100
keyCollection:
  # jwt密钥
  jwtKey: "4N7q5bXEvFQzqS1YCDSc+YXjlTEniAs83di6zg9pOVcYzIbJeaC5KDBCJz2+wGS3/qW9hE2wIY5E4Av9X7CJPg"
  # md5密钥
  md5Key: "siaC3MulRfAIdfapLPHLMEgMqR2jY5XqGpEwQRXrT3M4WwOrKyTAjKIyTT/7ZEdnUZ4C5ti7Fijk4aHT9GfbyQ"
